export type Listing = {
  id: string;
  title: string;
  courseCode: string;
  price: string | null;
  condition: "Like New" | "Good" | "Acceptable" | "Worn";
  description: string;
  campus: string;
  imageUrl: string | null;
  status: "ACTIVE" | "SOLD" | "PENDING_PAYMENT" | "PENDING_PAYMENT_REVIEW" | "PENDING_CONTENT_REVIEW" | "REJECTED" | "EXPIRED" | "WITHDRAWN";
  createdAt: string;
  paymentStatus?: "DUE" | "SUBMITTED" | "VERIFIED" | "REJECTED";
  moderationStatus?: "PENDING" | "APPROVED" | "REJECTED";
  paymentReviewReason?: string | null;
  moderationReviewReason?: string | null;
  expiresAt?: string | null;
  userId?: string;
  category: string;
  isTrade: boolean;
  tradeRequest?: string;
};
